spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    generate-unique-name: false
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ddl-auto: create
        database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
